### ISSUE TITLE
Markdown not working

### ISSUE THREAD

**Issue by ed588** [Cog-Creators/discord-embed-sandbox#1]
When I set values as shown in this image, we get a preview like this:
![image](https://cloud.githubusercontent.com/assets/19167629/26033439/5f0b1b64-38a4-11e7-969b-49e4bb469303.png)

However, when actually sending this embed, what gets show by discord is this:
![image](https://cloud.githubusercontent.com/assets/19167629/26033469/f4f7c2b2-38a4-11e7-966e-a22bc420b60f.png)

**Comment by orels1** [comment]
Thanks, ye, when I created this thing I forgot about markdown, will try to fix soon

**Comment by ed588** [comment]
ok

**Comment by fourjr** [comment]
:eyes:
