### ISSUE TITLE
Getting Code

### ISSUE THREAD

**Issue by CleverHost** [Cog-Creators/discord-embed-sandbox#6]
How do I exactly get the code to put in discord?

**Comment by NORXND** [comment]
![obraz](https://user-images.githubusercontent.com/26685237/83177203-ee75a680-a11e-11ea-8dc8-0a8c1d3632d6.png)
Just delete bot.say and enter ctx.send(embed=embed)

**Comment by ChrisGallardo** [comment]
You don't put the code into discord, this is meant to be used with [discord.py](https://github.com/Rapptz/discord.py), a wrapper for the [discord API](https://discord.com/developers/docs/intro).
